<a href="https://colab.research.google.com/github/rameshver43/Amazon/blob/main/Deep_Learning_for_computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors: Are Multi Dimensional Arrays



Array: is an ordered arrangement of numbers

0-D single element=> ex 8

[2 0 -3]  1-D array (1-D tensor)  shape=(3,)

2-D Tensor  
[1 2 0, 3 5 0]
shape= (2,3)

3-D Tensor
[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]
shape = (2,2,3)


In [3]:
import tensorflow as tf

In [6]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ])

print(tensor_two_d)


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


In [12]:
print(tensor_three_d.ndim)  # no of dim

3


In [13]:
print(tensor_three_d.shape)

(2, 4, 3)


In [14]:
tensor_four_d = tf.constant([[[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]],[[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]]])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]

  [[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]]


 [[[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]

  [[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]]], shape=(2, 2, 4, 3), dtype=int32)
